server:
  port: 8085

mybatis:
  type-aliases-package: com.example.myproject.dao.entity
  mapper-locations: classpath:mapper/*.xml


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myweb?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver